/**
 * Secure Mail — OpenPGP interoperability proof against GnuPG.
 *
 * Secure Mail's value depends on its output being standard OpenPGP
 * (RFC 4880 / RFC 9580 family) rather than a proprietary container: mail
 * encrypted today must stay readable by any conformant implementation, on any
 * platform, after the extension itself is gone. This script demonstrates that
 * by exchanging real messages with GnuPG in both directions, including
 * signature verification, and fails loudly on any mismatch.
 *
 *   A. Secure Mail encrypts + signs  ->  GnuPG decrypts + verifies
 *   B. GnuPG encrypts + signs        ->  Secure Mail decrypts + verifies
 *
 * The OpenPGP.js used is the one the extension bundles. GnuPG runs in a
 * throwaway home directory, so nothing touches the machine's real keyring.
 *
 * Usage: node scripts/interop-gnupg.mjs [outFile]
 */
import * as openpgp from '../node_modules/openpgp/dist/node/openpgp.mjs';
import {execFileSync} from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';

const OUT = process.argv[2] ||
  path.resolve(import.meta.dirname, '../../docs-sangkien/assets/measurements/interop-gnupg.json');

const GNUPGHOME = fs.mkdtempSync(path.join(os.tmpdir(), 'sm-interop-'));
fs.chmodSync(GNUPGHOME, 0o700);
const PASS = 'interop-passphrase';

// A Vietnamese payload with diacritics, so the test also proves the UTF-8 path
// survives a round trip through a different implementation.
const PLAINTEXT =
  'Báo cáo nghiệp vụ — nội dung được mã hóa đầu cuối theo chuẩn OpenPGP.\n' +
  'Ký tự tiếng Việt có dấu: ăâđêôơư ĂÂĐÊÔƠƯ — 1234567890.\n';

const gpg = (args, input) => execFileSync('gpg', [
  '--homedir', GNUPGHOME, '--batch', '--yes', '--pinentry-mode', 'loopback',
  '--passphrase', PASS, '--trust-model', 'always', ...args,
], {input, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024});

const results = [];
function check(name, detail, ok) {
  results.push({check: name, detail, result: ok ? 'PASS' : 'FAIL'});
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${name} — ${detail}`);
  if (!ok) { process.exitCode = 1; }
}

async function main() {
  console.log('GnuPG home:', GNUPGHOME);
  const gpgVersion = execFileSync('gpg', ['--version'], {encoding: 'utf8'}).split('\n')[0];
  const openpgpVersion = JSON.parse(fs.readFileSync(
    path.resolve(import.meta.dirname, '../node_modules/openpgp/package.json'))).version;
  console.log(gpgVersion, '/ openpgp', openpgpVersion, '\n');

  // --- identities ------------------------------------------------------
  // Secure Mail side, generated by the library the extension ships.
  const sm = await openpgp.generateKey({
    type: 'rsa', rsaBits: 4096,
    userIDs: [{name: 'Secure Mail User', email: 'securemail@donvi.test'}],
    passphrase: PASS, format: 'object',
  });
  const smPriv = await openpgp.decryptKey({privateKey: sm.privateKey, passphrase: PASS});

  // GnuPG side.
  // A parameter file, so the key definitely gets an encryption subkey.
  // --quick-generate-key with usage "default" produces a sign/certify-only key.
  gpg(['--gen-key'], [
    'Key-Type: RSA', 'Key-Length: 4096',
    'Subkey-Type: RSA', 'Subkey-Length: 4096',
    'Name-Real: GnuPG User', 'Name-Email: gnupg@donvi.test',
    'Expire-Date: 0', `Passphrase: ${PASS}`, '%commit', '',
  ].join('\n'));
  const gpgPubArmored = gpg(['--armor', '--export', 'gnupg@donvi.test']);
  const gpgPub = await openpgp.readKey({armoredKey: gpgPubArmored});
  gpg(['--import'], sm.publicKey.armor());

  check('Key import (Secure Mail -> GnuPG)',
    'GnuPG accepted the RSA-4096 public key produced by OpenPGP.js',
    gpg(['--list-keys']).includes('securemail@donvi.test'));
  check('Key import (GnuPG -> Secure Mail)',
    `OpenPGP.js parsed the GnuPG key, fingerprint ${gpgPub.getFingerprint().toUpperCase().slice(0, 16)}…`,
    gpgPub.getUserIDs().some(u => u.includes('gnupg@donvi.test')));

  // --- direction A: Secure Mail -> GnuPG --------------------------------
  const armoredA = await openpgp.encrypt({
    message: await openpgp.createMessage({text: PLAINTEXT}),
    encryptionKeys: gpgPub,
    signingKeys: smPriv,
  });
  const gpgOut = execFileSync('gpg', [
    '--homedir', GNUPGHOME, '--batch', '--yes', '--pinentry-mode', 'loopback',
    '--passphrase', PASS, '--trust-model', 'always', '--status-fd', '2', '--decrypt',
  ], {input: armoredA, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe']});

  check('A. Confidentiality (Secure Mail -> GnuPG)',
    'GnuPG recovered the plaintext byte-for-byte, diacritics intact',
    gpgOut === PLAINTEXT);

  let statusA = '';
  try {
    statusA = execFileSync('sh', ['-c',
      `gpg --homedir '${GNUPGHOME}' --batch --yes --pinentry-mode loopback ` +
      `--passphrase '${PASS}' --trust-model always --status-fd 1 --decrypt 2>/dev/null`],
      {input: armoredA, encoding: 'utf8'});
  } catch { /* status parsed below */ }
  check('A. Authenticity (Secure Mail -> GnuPG)',
    'GnuPG reported GOODSIG for the Secure Mail signature',
    /GOODSIG|VALIDSIG/.test(statusA));

  // --- direction B: GnuPG -> Secure Mail --------------------------------
  const armoredB = gpg(['--armor', '--encrypt', '--sign',
    '--recipient', 'securemail@donvi.test', '--local-user', 'gnupg@donvi.test'], PLAINTEXT);
  const decB = await openpgp.decrypt({
    message: await openpgp.readMessage({armoredMessage: armoredB}),
    decryptionKeys: smPriv,
    verificationKeys: gpgPub,
  });
  check('B. Confidentiality (GnuPG -> Secure Mail)',
    'OpenPGP.js recovered the plaintext byte-for-byte, diacritics intact',
    decB.data === PLAINTEXT);

  let sigBValid = false;
  try { sigBValid = await decB.signatures[0].verified; } catch { sigBValid = false; }
  check('B. Authenticity (GnuPG -> Secure Mail)',
    'OpenPGP.js verified the GnuPG signature against the imported public key',
    sigBValid === true);

  // --- detached signature, both directions ------------------------------
  const detached = await openpgp.sign({
    message: await openpgp.createMessage({text: PLAINTEXT}),
    signingKeys: smPriv, detached: true,
  });
  fs.writeFileSync(path.join(GNUPGHOME, 'msg.txt'), PLAINTEXT);
  fs.writeFileSync(path.join(GNUPGHOME, 'msg.sig'), detached);
  let verifyOk = true;
  try {
    execFileSync('gpg', ['--homedir', GNUPGHOME, '--batch', '--trust-model', 'always',
      '--verify', path.join(GNUPGHOME, 'msg.sig'), path.join(GNUPGHOME, 'msg.txt')],
      {stdio: 'pipe'});
  } catch { verifyOk = false; }
  check('C. Detached signature (Secure Mail -> GnuPG)',
    'GnuPG verified a detached signature produced by Secure Mail',
    verifyOk);

  // --- tamper detection -------------------------------------------------
  // Flip one base64 character in the body of the armor; the MDC/AEAD integrity
  // check must reject it rather than returning corrupted plaintext.
  const lines = armoredB.split('\n');
  const bodyIdx = lines.findIndex((l, i) => i > 2 && l.length > 40 && !l.startsWith('-----'));
  const ch = lines[bodyIdx][10];
  lines[bodyIdx] = lines[bodyIdx].slice(0, 10) + (ch === 'A' ? 'B' : 'A') + lines[bodyIdx].slice(11);
  let rejected = false;
  try {
    const r = await openpgp.decrypt({
      message: await openpgp.readMessage({armoredMessage: lines.join('\n')}),
      decryptionKeys: smPriv, verificationKeys: gpgPub,
    });
    rejected = r.data !== PLAINTEXT;
  } catch { rejected = true; }
  check('D. Integrity (tampered ciphertext)',
    'A single flipped character in the ciphertext is rejected, not silently mis-decrypted',
    rejected);

  const report = {
    generatedAt: new Date().toISOString(),
    gnupg: gpgVersion, openpgpjs: `openpgp ${openpgpVersion}`,
    payload: 'UTF-8 Vietnamese text with diacritics',
    keyType: 'RSA-4096 on both sides',
    results,
    summary: results.every(r => r.result === 'PASS') ? 'ALL PASS' : 'FAILURES PRESENT',
  };
  fs.mkdirSync(path.dirname(OUT), {recursive: true});
  fs.writeFileSync(OUT, JSON.stringify(report, null, 2));
  console.log('\n' + report.summary, '->', OUT);
  fs.rmSync(GNUPGHOME, {recursive: true, force: true});
}

main().catch(e => { console.error(e); fs.rmSync(GNUPGHOME, {recursive: true, force: true}); process.exit(1); });
